[project]
name = "sparcoular"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acoular>=25.10",
    "matplotlib>=3.10.7",
]
